### PR TITLE
Nativescript 8 support

### PR DESCRIPTION
**Pull request by pjabang1**

### CODE REVIEW

**Review by abhayastudios — APPROVED** [review]

**Comment by abhayastudios** [comment]
@pjabang1 Thanks!

**Review by abhayastudios — COMMENTED** [review]
Seems legit. Thanks @pjabang1!

**Comment by abhayastudios** [comment]
Still having issues with NS8 though what seems to be due to the web workers not working, see https://github.com/NativeScript/worker-loader/issues/72.

**Comment by pjabang1** [comment]
> NativeScript/worker-loader#72

@abhayastudios I will look into this

**Pull request merged**
